name: Pre-commit checks

on:
  pull_request:
    branches:
      - bagnaram/remote-spark-jar

  push:
    branches:
      - bagnaram/remote-spark-jar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: fmt check
        run: make fmt-check

      - name: unit tests
        run: make test

  it:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: log in to container registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Spark-Operator Docker Image
        run: |
          #tag=$(git describe --tags --dirty)_v3.1.1
          tag=`git rev-parse HEAD`
          docker build -t quay.io/crawl_soever/spark-operator:${tag} .
          docker build -t quay.io/crawl_soever/spark-operator:local .
          docker push quay.io/crawl_soever/spark-operator:${tag}

#      - name: Build Spark-Operator Docker Image
#        run: |
#          #tag=$(git describe --tags --dirty)_v3.1.1
#          tag=`git rev-parse HEAD`
#          docker build -t quay.io/crawl_soever/spark-operator:${tag} .
#          docker build -t quay.io/crawl_soever/spark-operator:local .

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Print ct version information and List files
        run: ct version && ls -lh

      - name: Run chart-testing (lint)
        run: ct lint

      - name: Detect CRDs drift between chart and manifest
        run: make detect-crds-drift

      - name: setup minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: "v1.24.0"
          kubernetes version: "v1.20.8"
          start args: --memory 6g --cpus=2 --addons ingress
          github token: ${{ inputs.github-token }}

      - name: Run chart-testing (install)
        run: |
          tag=$(git describe --tags --dirty)_v3.1.1
          minikube image load quay.io/crawl_soever/spark-operator:local
          ct install

      # The integration tests are currently broken see: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1416
      # - name: Run chart-testing (integration test)
      #   run: make it-test
      
      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
