name: CI

on:
  push:
    branches: [ relativity-main ]
  pull_request:
    branches: [ relativity-main ]

jobs:
  build-spark-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run gofmt check
        run: make fmt-check

      - name: Run static analysis
        run: make static-analysis

      - name: Run unit tests
        run: make unit-test

      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.KEY_VAULT }}
          secrets: "acrUsername, acrPassword"
        id: kv

      - name: Login to docker
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ steps.kv.outputs.acrUsername }}
          password: ${{ steps.kv.outputs.acrPassword }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.IMAGE }}
          flavor: |
            latest=false
            prefix=v1beta2-1.3.3-3.2.1-

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SPARK_IMAGE=${{ secrets.BASE_IMAGE }}
  
  build-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Print chart-testing version information
        run: ct version

      - name: Run chart-testing (lint)
        run: ct lint